to: 4.19.2
from: ^4[.]18[.]1[6-8][+].*$
url: https://issues.redhat.com/browse/MON-4270
name: AlertmanagerV1NotSupported
message: |-
  Upgrade to OpenShift 4.19 will fail on cluster monitoring operator in case API version v1 of Alertmanager
  is still specified in the ConfigMaps "cluster-monitoring-config" or "user-workload-monitoring-config".
matchingRules:
- type: Always
